# Generated by Django 4.0.2 on 2022-02-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField()),
                ('super_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_one', to='supers.supers')),
                ('super_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_two', to='supers.supers')),
            ],
        ),
    ]
